### ISSUE TITLE
How to feature image on a page (not a blog post).

### ISSUE THREAD

**Issue by austinkocher** [LawandSpace/Law-Space-Website#17]
I added an image to the page "Write for Us", but the image does not appear in the social media card of Twitter or Facebook. I had tried to include the image in the YAML front matter using "image: [file path]" but that didn't work. So I guess, two questions: (1) Is it possible to feature an image on a page, not just a blog post, and (2) How can we make the image on the "write for us" page get picked up by social media? Maybe this issue is premature and if I just wait a while, the image will get "recognized" by the Internet or something.

**Comment by austinkocher** [comment]
By waiting a few minutes, it seems to have solved the issue of social media not picking up on the image. Facebook and LinkedIn now catch the image, although Twitter has not recognized it yet. So maybe it's just a matter of time. Although I still don't understand if we can add an image in the YAML front matter on pages.

**Comment by Riwajchalise** [comment]
To help Twitter decide which image to use, I made the necessary adjustments to the about page's layout and markdown files please check. The problem is that Twitter only recognized an image if it was present in the page's meta tag. Now we can add images in other pages if needed, such as on the about page and the twitter card will identify the thumbnail image. This will take some time to take effect. I hope I could make you understand. :)

**Comment by austinkocher** [comment]
Thank you, that makes sense. Glad to see that the issue is fixed!!
