### ISSUE TITLE
Can we move all individual pages into a folder marked "pages" to clean it up?

### ISSUE THREAD

**Issue by austinkocher** [LawandSpace/Law-Space-Website#9]

**Comment by Riwajchalise** [comment]
Yes. I have fixed this too. There is a folder in the root directory named pages. Just make sure to add a permalink variable to define the path of your URL. I have added in your new pages [https://lawandspace.com/how-to-write/](https://lawandspace.com/how-to-write/) and [https://lawandspace.com/how-to-edit/](https://lawandspace.com/how-to-edit/) pages, Otherwise the URL of the pages will have **pages/<filename>** format.

Suppose you find difficulty understanding clone the latest changes and check the pages folder. If there is still something that you do not understand please write to me.

Thanks
